/*
 *  gcc -Wall sigquit.c -o sigquit
 *  SIGQUIT default: terminate and dump core
 *  kill -SIGQUIT <pid>
 *  kill -3 <pid>
 *  Ctrl-\
 *
 *  para que se genere el core dump ejecutar "ulimit -c 1024" (o ulimit -c unlimited)
 *  luego se generar el core dump (archivo core)
 *  para ver el core dump ejecutar: gdb ./sigquit core:
 *
 *  Core was generated by `./sigquit'.
 *  Program terminated with signal SIGQUIT, Quit.
 *
 */
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>

void handler(int signal_number)
{
    printf("SIGQUIT recived!\n");
    signal(SIGQUIT, SIG_DFL); // restablezco el handler para que termine y genere el core dump la segunda vez
}

int main()
{
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = &handler;
    if (sigaction(SIGQUIT, &sa, NULL) != 0)
    {
        perror("signal()");
    }

    pid_t pid;

    pid = getpid();
    fprintf(stderr, "pid=%d\n", pid);

    while (1)
        sleep(2);

    return 0;
}
